######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 5 16:37:52 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += fastDraw.h
SOURCES += fastDraw.cpp main.cpp

QT += opengl xml
LIBS += -lQGLViewer -lglut -lGLU -lGL -lm

