######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 5 13:40:31 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += simpleViewer.h
SOURCES += main.cpp simpleViewer.cpp

QT += opengl xml
LIBS += -lQGLViewer -lglut -lGLU -lGL -lm

