######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 5 14:06:16 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += manipulatedFrameSetConstraint.h multiSelect.h object.h
SOURCES += main.cpp manipulatedFrameSetConstraint.cpp multiSelect.cpp object.cpp

QT += opengl xml
LIBS += -lQGLViewer -lglut -lGLU -lGL -lm

