######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 15 18:58:50 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += main.h eventsWindow.h xmlEditor.h tabsWindow.h
FORMS += eventsWindow.ui xmlEditor.ui tabsWindow.ui
SOURCES += main.cpp eventsWindow.cpp xmlEditor.cpp tabsWindow.cpp

QT += network xml gui

