######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 5 13:29:33 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += glwidget.h window.h
SOURCES += glwidget.cpp main.cpp window.cpp

QT += opengl

