#!/bin/bash

ETH0_IF_ADDR=192.168.223.2

## don't use "0.0.0.0" in TRANSPORT_BIND_ADDR
TRANSPORT_BIND_ADDR="192.168.1.7:22102"
INCOMING_LINK_ADDR="s:77.41.111.214:22102"
HUID="2210:0:7309:227d:3030:fb23:816a:cc5d"
DEBUG=1
IPNOISE_CONF=/etc/ipnoise/profile/config_home.xml

. notebook_setup_base
. host_setup

