#!/bin/bash

ETH0_IF_ADDR=192.168.222.2

## don't use "0.0.0.0" in TRANSPORT_BIND_ADDR
TRANSPORT_BIND_ADDR="195.218.191.221:22101"
HUID="2210:0:7309:227d:3030:fb23:816a:cc5f"
DEBUG=6
IPNOISE_CONF=/etc/ipnoise/profile/config_work.xml

. notebook_setup_base
. host_setup

