######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 5 14:48:17 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mouseGrabber.h
SOURCES += main.cpp mouseGrabber.cpp

QT += opengl xml
LIBS += -lQGLViewer -lglut -lGLU -lGL -lm

