######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 5 13:58:25 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += select.h
SOURCES += main.cpp select.cpp

QT += opengl xml
LIBS += -lQGLViewer -lglut -lGLU -lGL -lm

